server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://mdshlqipcuihti:4123f9f3089a608d5899af0b84ad283f026382ab604ee715543870888f0cd850@ec2-52-4-111-46.compute-1.amazonaws.com:5432/dc91u6o4jn8e71
    username: mdshlqipcuihti
    password: 4123f9f3089a608d5899af0b84ad283f026382ab604ee715543870888f0cd850

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: true

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend