server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://zqycbflcsvejqp:b03033b7bd8d7646959004e6dd6693603a70b6fac05d3a8f9900f546f5862dca@ec2-54-163-97-228.compute-1.amazonaws.com:5432/d217ultr8lrvku
    username: zqycbflcsvejqp
    password: b03033b7bd8d7646959004e6dd6693603a70b6fac05d3a8f9900f546f5862dca

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend
